version: '3.4'
services:
  golang:
    image: golang:1.12-alpine
    env_file: .env
    volumes:
      - .:/go/src/{{cookiecutter.app_go_package_path}}
    working_dir: /go/src/{{cookiecutter.app_go_package_path}}

  serverless:
    image: amaysim/serverless
    env_file: .env
    volumes:
      - ~/.aws:/root/.aws
      - .:/opt/app
    working_dir: /opt/app

  auth:
    image: contino/aws-google-auth
    env_file: .env
    volumes:
      - ~/.aws:/root/.aws
      